version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
      - '24678:24678'
    env_file:
      - ./frontend/.env
